### ISSUE TITLE
Where would sagemiddleware.run(sagefn) be called

### ISSUE THREAD

**Issue by vidjuheffex** [naviapps/nw-react-boilerplate#8]
I don't usually have my store creation stuff split out.

Where would you call the .run method (since index.js doesn't have sagemiddleware)

**Comment by vidjuheffex** [comment]
Also, how can you get Sagas to work? 
I get : 
`
Uncaught ReferenceError: regeneratorRuntime is not defined
`
Anytime I use a generator

**Comment by naviapis** [comment]
Added redux-saga process.
https://github.com/naviapps/nw-react-boilerplate/commit/d0e1e0ff4ee7f64b67d3c887671dcafe8ac1726e

nw-react-boilerplate has changed significantly since `v0.1.0`.
[`nw-react-scripts`](https://github.com/naviapps/nw-react-scripts) is included in the back end.
As a result, generators were also supported at the same time.

Thanks.

**Comment by vidjuheffex** [comment]
Thanks! I ended up adding 
`import regeneratorRuntime from "regenerator-runtime";`

and that got me up and running in that sense with my first saga. I also realized the run sage method can be run within the createStore, before the store is returned. 

Very cool project!
